// Code generated by "stringer -type ErrCode -linecomment -output code_string.go"; DO NOT EDIT.

package e

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SUCCESS-10000]
	_ = x[ERROR-10001]
	_ = x[INVALID_PARAMS-10002]
	_ = x[ERROR_EXIST_TAG-10003]
	_ = x[ERROR_NOT_EXIST_TAG-10004]
	_ = x[ERROR_NOT_EXIST_ARTICLE-10005]
	_ = x[ERROR_AUTH_CHECK_TOKEN_FAIL-10006]
	_ = x[ERROR_AUTH_CHECK_TOKEN_TIMEOUT-10007]
	_ = x[ERROR_AUTH_TOKEN-10008]
	_ = x[ERROR_AUTH-10009]
}

const _ErrCode_name = "okfail请求参数错误已存在该标签名称该标签不存在该文章不存在Token鉴权失败Token已超时Token生成失败Token错误"

var _ErrCode_index = [...]uint8{0, 2, 6, 24, 48, 66, 84, 101, 115, 132, 143}

func (i ErrCode) String() string {
	i -= 10000
	if i < 0 || i >= ErrCode(len(_ErrCode_index)-1) {
		return "ErrCode(" + strconv.FormatInt(int64(i+10000), 10) + ")"
	}
	return _ErrCode_name[_ErrCode_index[i]:_ErrCode_index[i+1]]
}
