// Code generated by "stringer -type ErrCode -linecomment -output code_string.go"; DO NOT EDIT.

package e

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SUCCESS-0]
	_ = x[ERROR-10001]
	_ = x[INVALID_PARAMS-10002]
	_ = x[ERROR_EXIST_TAG-10003]
	_ = x[ERROR_NOT_EXIST_TAG-10004]
	_ = x[ERROR_NOT_EXIST_ARTICLE-10005]
	_ = x[ERROR_AUTH_CHECK_TOKEN_FAIL-10006]
	_ = x[ERROR_AUTH_CHECK_TOKEN_TIMEOUT-10007]
	_ = x[ERROR_AUTH_TOKEN-10008]
	_ = x[ERROR_AUTH-10009]
}

const (
	_ErrCode_name_0 = "ok"
	_ErrCode_name_1 = "fail请求参数错误已存在该标签名称该标签不存在该文章不存在Token鉴权失败Token已超时Token生成失败Token错误"
)

var (
	_ErrCode_index_1 = [...]uint8{0, 4, 22, 46, 64, 82, 99, 113, 130, 141}
)

func (i ErrCode) String() string {
	switch {
	case i == 0:
		return _ErrCode_name_0
	case 10001 <= i && i <= 10009:
		i -= 10001
		return _ErrCode_name_1[_ErrCode_index_1[i]:_ErrCode_index_1[i+1]]
	default:
		return "ErrCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
